---
title: "Conflicto y Cohesion Social"
author: "Vicente Godoy"
date: "2022-11-30"
output: html_document
---

### **Abstract**

En chile, ha aumentado la sensacion de inseguridad, o al menos se ha manifestado- sea en la televison o en las redes sociales- todas las inseguridad de la pobacion chilena .Por ende, es de suma importancia lograr responder el Por qué surge este sentimiento de inseguridad y qué factores inciden  en esta percepcion de los y las chilenas. Por lo cual, se recogieron datos sobre 4 variables que pudiesen incidir sobre la inseguridad, a saber: a)percepcion de conflicto entre chilesnos e inmigrantes peruanos. b) justificacion de la violencia. c) Confianza en Carabineros. d) Edad. Los resultados, a grandes razgos, indicaron que, en primer lugar, aquellos que perciben mas conflictos entre hombres y mayores son menos seguros; aquellas que nunca justifican la violencia se sienten mas seguros; aquellos que nunca justifican la violencia se sienten mas seguros; y, finalmente, los adultos jovenes (de 18 a 26) son la poblacion menos segura


### **Introduccion**

En chile, producto de la revuelta social acontecida el 18 de Octubre de 2019 y producto de la pandemia que tendría su origen el 3 de marzo de 2020, comenzó un aparente o concreta subida de inseguridad social en la población chilena. El contenido de la información que se mostraban en los canales de televisión y en las redes sociales fue de una oleada incontrolable de noticias negativas que provocaba la necesidad de seguridad por parte del Estado y de una cantidad selecta de instituciones -pues con la revuelta la confianza en algunas instituciones como las fuerzas armadas quedaron fuera. 
En consecuencia, independiente de si la inseguridad sea mera percepción, es relevante indagar sobre aquellas fuerzas o situaciones sociales que inciden sobre la inseguridad social, o al menos comprender las situaciones que inciden sobre el comportamiento de las personas que las vuelven inseguras. A causa de esta situacion, la presenta investigacion indagó sobre algunos factores que podrian incidir en la seguridad y descubrir el perfil de los y las inseguras debido a situaciones sociales, ellas fueron, a saber: el conflicto entre chilenos y peruanos, el tramo de edad, la confianza en carabineros y la confianza en carabineros. Ademas, es relevante indagar sobre variables sociales puesto que, como señala Luneke (2021) " la seguridad se hace cuidándose unos a otros, de manera asociativa, nunca solos". Dicho de otra manera, mas alla de recaer en el autocuidado para prevenir y enfrentar la inseguridad, se debe indagar sobre lo social para lograr revertir la inseguridad en Chile


### **Analisis**

Dado que la presente investigacion tiene pretensiones de descubrir factores que gatillan la inseguridad en las personas y que las vuelve inseguras, el presente estudio extrajo informacion procesada de la base de datos del Estudio Longitudinal Social de Chile (ELSOC) 2016-2021. Para aquello, se utilizó las funciones de: group_by para agrupar dos variables y reconocer su correlacion; summarise para calcular con un 99% de confianza y 1% de significacnia la relacion y los intervalos de confianza; mutate para obtener resultados con proporcion; y finalmente ungroup.
En primer lugar se hizo analisis de la correlacion entre la percepcion de inseguridad y la percepcion de conflicto entre chilenos y peruanos. Para aquellos ambas se recodificaron: por un lado t10 se recodificó en tres opciones que fueron seguro, inseguro y ni seguro ni inseguro. Por otro lado, la variable f01_05 tambien se recodificó en tres respuestas que son "conflictos menores", "conflictos mayores y "ningun conflicto". Posterior a esta recodificacion, los resultado fueron que el 71,4% de aquellos que no perciben conflictos entre chilenos y peruanos son seguros, 78,9% de aquellas que perciben conflictos menores son seguros y 62,4% aquellos que perciben conflictos mayores son seguros.
En segundo lugar, se correlacionó las variables de inseguridad y justificacion de la violencia (que estudiantes tiren piedras a carabineros). Esta ultima cabe señalar que se recodificó en tres opciones: "Nunca se justifica", "En ocasiones se justifica" y "En general se justifica". Los resultados fueron que el 68,1% de aquellas personas que nunca se justifica son seguras, un 63.4% los partidarios que en ocasiones se justifica y  57,9% los que en general se justifica.
En tercer lugar, se analizó la relacion entre inseguridad y confianza en Carabineros, el cual este ultimo fue recodicado en "Nada de confianza", "Bastante confianza", y "Algo de confianza". En cuanto a los resultados fueron que el 61.4% de los que no confian nada en carabineros son seguros, 68,1% quienes confian algo en carabineros son seguros y 66,7% los que confian bastante en carabineros.
En cuarto y ultimo lugar, se aplicó la relacion entre la inseguridad y la edad, el cual esta ultima variable fue recodificada en tramos, el cual de los 18 años hasta los 26 años se mencionan como "Adultos jovenes", de los 27 años a los 59 años como "Adultos" y finalmente de los 60 años en adelante como "adultos mayores". Luego de esta recodificacion los resultados fueron que el 74,1% de los adultos mayores son seguros, el 63,9% de los adultos son seguros y el 49,4% de los adultos jovenes son seguros.


### **Conclusion**

En definitiva, 

#t10:	Percepcion de seguridad del barrio
#f01_02:	Percepcion de conflictos: Entre hombres y mujeres
#f05_07:	Justificacion de violencia: Estudiantes tiren piedras a carabineros
#c05_03:	Grado de confianza: Carabineros
#m0_edad:	Edad del entrevistado

T?tulo, Abstract (100-150 palabras), Introducci?n (200-250 palabras), An?lisis (300-500 palabras), Conclusi?n (150-200 palabras) y Referencias. Debe indicar su nombre, profesora y ayudantes


